name: mysusenas
description: Sakernas Agustus

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  anim_search_bar: ^2.0.2
  animation_search_bar: ^0.0.9
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  charts_flutter: ^0.12.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  get_storage: ^2.0.3
  grouped_list: ^5.1.2
  gsheets: ^0.4.2
  intl: ^0.17.0
  latlong_to_osgrid: ^1.3.2
  location: ^4.3.0
  lottie: ^1.2.1
  nanoid: ^1.0.0
  pattern_formatter: ^2.0.0
  percent_indicator: ^4.2.2
  photo_view: ^0.14.0
  pull_to_refresh: ^2.0.0
  searchbar_animation: ^0.0.2
  url_launcher: ^6.0.10
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/raster/logo1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/raster/.
    - assets/images/vector/.
    - assets/images/susenas/.
    - assets/animasi/.
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
